# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9f8234d7a99bc7321424d5af0464d8c44d4d28edcefcaa009d84d7a3c58b5737628e7bfadb8e69b838849259e5f4859d7c53beefadd0c6467f47f359fa8c641

test:
  secret_key_base: 5ac182203d01717e1c49cea4f75a0b488f6c6214149f0a95c56da88c6940571bab177b574dccd3a03a9d99c95f50a28a9be6916c2b20f491e531f335e87f0dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
